version: 2
jobs:
  build:
    docker:
      - image: alekzonder/puppeteer:1.1.1
    environment:
      - ARTIFACT_PATH: /home/pptruser/project/artifacts
    steps:
      - checkout
      - run:
          name: Create artifacts directory
          command: mkdir -p /home/pptruser/project/artifacts
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Install
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Compile
          command: yarn build
      - run: 
          name: Tests
          command: yarn test
      - store_artifacts:
          path: /home/pptruser/project/artifacts
  container:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Container
          command: docker build -t nathf/puppeteer-healthcheck:${CIRCLE_TAG:1}
      - run:
          name: Docker Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Docker Push
          command: docker push nathf/puppeteer-healthcheck:${CIRCLE_TAG:1}
  npm_publish:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Setup
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Compile
          command: yarn build
      - run:
          name: Publish
          command: |
            npm --no-git-tag-version version ${CIRCLE_TAG:1}
            npm publish
  release_gate:
    docker:
      - image: alpine
    steps:
      - run: "echo 'noop'"

workflows:
  version: 2
  puppeteer_healthcheck:
    jobs:
      - build
      - container:
          requires:
            - release_gate
      - npm_publish:
          requires:
            - release_gate
      - release_gate:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
