version: 2
jobs:
  build:
    docker:
      - image: alekzonder/puppeteer:1.1.1
    environment:
      - ARTIFACT_PATH: /home/pptruser/project/artifacts
    steps:
      - checkout
      - run:
          name: Create artifacts directory
          command: mkdir -p /home/pptruser/project/artifacts
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Install
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Flow
          command: yarn flow check
      - run:
          name: Compile
          command: yarn build
      - run: 
          name: Tests
          command: yarn test
      - run:
          name: Upload Coverage
          command: bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /home/pptruser/project/artifacts
  docker_push:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Container
          command: ./.circleci/docker-build.sh
  npm_publish:
    docker:
      - image: node:8.9.4-alpine
    steps:
      - checkout
      - run:
          name: Setup
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Install
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Compile
          command: yarn build
      - run:
          name: Publish
          command: |
            npm --no-git-tag-version version ${CIRCLE_TAG:1}
            npm publish --access public

workflows:
  version: 2
  puppeteer_healthcheck:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^.*/
  puppeteer_healthcheck_tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - docker_push:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
      - npm_publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
