version: 2
jobs:
  build:
    docker:
      - image: alekzonder/puppeteer:1.1.1
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run:
          name: Install
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Compile
          command: yarn build
      - run: 
          name: Tests
          command: yarn test